import type { Metadata } from 'next'
import { Playfair } from 'next/font/google'
const playfair = Playfair({ subsets: ['latin'] })

import './globals.css'

export const metadata: Metadata = {
  title: 'Pinturas Van Gogh',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={playfair.className}>{children}</body>
    </html>
  )
}
